### ISSUE TITLE
Distance.to doesn't seem to calculate geodesic distances correctly

### ISSUE THREAD

**Issue by andersmusikkahs** [StephanGeorg/Distance.to-Issues#2]
The distance from
LAX: 33.9421135,-118.4070574
to:
ARN: 59.6352,17.9125
is calculated by distance.to as 8864.37 km.

However, using the well-known opensource library 'proj', and other methods, the real distance between those two sets of lat/lon coordinates on earth using WGS84 ellipsoid, seems to be 8885.972248 km. Does distance.to perhaps make its calculations using a spherical earth model?

**Comment by StephanGeorg** [comment]
>  Does distance.to perhaps make its calculations using a spherical earth model?

Yes, you're right. The distance shown on distance.to are calculated with haversine formula.
